import { expect, test } from "@playwright/test";
import { signInThroughUI } from "./auth";

test("compare historical evaluations, score a case and review an instruction candidate into a draft", async ({ page }, testInfo) => {
  const identity = await signInThroughUI(page);
  const errors: string[] = []; page.on("pageerror", (error) => errors.push(error.message));
  const headers = { "x-csrf-token": identity.csrf_token };
  async function resource(kind: string, slug: string, spec: object) {
    const response = await page.request.post("/api/v1/resources", { headers, data: { kind, name: slug, slug, spec } });
    expect(response.status(), await response.text()).toBe(201);
    const item = await response.json();
    expect((await page.request.post(`/api/v1/resources/${item.id}/publish`, { headers, data: { revision: item.revision } })).status()).toBe(201);
    return { id: item.id, version: 1 };
  }
  const model = await resource("model", "evaluation-model", { provider: "demo", model: "demo" });
  const prompt = await resource("prompt", "evaluation-prompt", { template: "Original evaluation instructions" });
  const agent = await resource("agent", "evaluation-agent", { model_ref: model, prompt_refs: [prompt] });
  const current = await (await page.request.get(`/api/v1/resources/${agent.id}`)).json();
  const changed = await (await page.request.put(`/api/v1/resources/${agent.id}`, { headers, data: { name: current.name, revision: current.revision, spec: { ...current.draft, greeting: "Second release" } } })).json();
  expect((await page.request.post(`/api/v1/resources/${agent.id}/publish`, { headers, data: { revision: changed.revision } })).status()).toBe(201);
  await page.getByRole("button", { name: "07 Evaluations", exact: true }).click();
  const create = page.getByRole("form", { name: "Create evaluation set" });
  await create.getByLabel("Name", { exact: true }).fill("Browser regression set");
  await create.getByLabel("Cases JSON").fill(JSON.stringify([{ input: "hello", expected: "unmatched-expected-result", match: "exact" }]));
  await create.getByRole("button", { name: "Save test set", exact: true }).click();
  const launch = page.getByRole("form", { name: "Run evaluation", exact: true });
  await launch.getByLabel("Published Agent").selectOption(agent.id);
  await launch.getByLabel("Release version").selectOption("1");
  async function run() {
    const response = page.waitForResponse((response) => response.url().includes("/evaluations/") && response.url().endsWith("/run") && response.request().method() === "POST");
    await launch.getByRole("button", { name: "Run evaluation", exact: true }).click();
    const item = await (await response).json();
    await expect(page.getByRole("region", { name: "Evaluation details", exact: true }).getByRole("status")).toHaveText("completed");
    return item.id;
  }
  const baseline = await run();
  await launch.getByLabel("Release version").selectOption("2");
  const candidate = await run();
  const details = page.getByRole("region", { name: "Evaluation details", exact: true });
  const result = details.getByRole("article", { name: "Evaluation case 1", exact: true });
  await result.getByText("Add human review", { exact: true }).click();
  await result.getByLabel("Human score").fill("0.5");
  await result.getByLabel("Review note").fill("Useful answer, but missing the required format");
  await result.getByRole("button", { name: "Save human review", exact: true }).click();
  await expect(result).toContainText("Human review: 50%");
  await expect(result).toContainText("rule 0%");
  const proposal = details.getByRole("form", { name: "Propose improvement" });
  await proposal.getByLabel("Instruction resource").selectOption(prompt.id);
  await expect(proposal.getByLabel("Current draft instructions")).toHaveValue("Original evaluation instructions");
  await proposal.getByLabel("Proposed instructions").fill("Revised instructions: follow the requested output format.");
  await proposal.getByLabel("Rationale").fill("The first evaluation case missed the output format.");
  await proposal.getByRole("button", { name: "Submit candidate", exact: true }).click();
  const card = details.getByRole("article", { name: /^Improvement / });
  await card.getByText("Inspect proposed change", { exact: true }).click();
  await expect(card).toContainText("Original evaluation instructions");
  await expect(card).toContainText("Revised instructions:");
  await card.getByLabel("Decision note").fill("Reviewed against the failing case; apply to draft for retesting.");
  await card.getByRole("button", { name: "Accept into draft", exact: true }).click();
  await expect(card.getByRole("heading", { name: "Candidate · accepted", exact: true })).toBeVisible();
  const after = await (await page.request.get(`/api/v1/resources/${prompt.id}`)).json();
  expect(after.draft.template).toContain("Revised instructions");
  expect(after.active_version).toBe(1); expect(after.latest_version).toBe(1);
  const published = await (await page.request.get(`/api/v1/resources/${prompt.id}/versions/1`)).json();
  expect(published.spec.template).toBe("Original evaluation instructions");
  const comparison = page.getByRole("form", { name: "Compare evaluations" });
  await comparison.getByLabel("Baseline batch").selectOption(baseline);
  await comparison.getByLabel("Candidate batch").selectOption(candidate);
  await comparison.getByRole("button", { name: "Compare batches", exact: true }).click();
  const view = page.getByRole("region", { name: "Evaluation comparison", exact: true });
  await expect(view).toContainText("v1 → v2");
  await expect(view).toContainText("0 improved · 0 regressed");
  await expect(view).toContainText("Human: 50%");
  await page.setViewportSize({ width: 1440, height: 1100 });
  await page.screenshot({ path: testInfo.outputPath("evaluation-center.png"), fullPage: true });
  await page.reload();
  await page.getByRole("button", { name: "07 Evaluations", exact: true }).click();
  await page.getByRole("button", { name: `Inspect evaluation ${candidate}`, exact: true }).click();
  await expect(page.getByRole("heading", { name: "Candidate · accepted", exact: true })).toBeVisible();
  await expect(page.getByRole("article", { name: "Evaluation case 1", exact: true })).toContainText("Human review: 50%");
  expect(errors).toEqual([]);
});
