import { expect, test } from "@playwright/test";
import { signInThroughUI } from "./auth";

test("publish edits, compare releases, rollback, archive/restore and reject stale resource edits", async ({ page }) => {
  const identity = await signInThroughUI(page);
  const errors: string[] = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.getByRole("button", { name: "03 Resources", exact: true }).click();
  await page.getByRole("button", { name: "+ New resource", exact: true }).click();
  const creator = page.getByRole("dialog", { name: "Create resource" });
  await creator.getByRole("combobox", { name: "Type", exact: true }).selectOption("prompt");
  await creator.getByRole("textbox", { name: "Name", exact: true }).fill("Release notes");
  await creator.getByRole("textbox", { name: "Slug", exact: true }).fill("release-notes");
  await creator.getByRole("textbox", { name: "Template", exact: true }).fill("Alpha instructions");
  await creator.getByRole("button", { name: "Create draft", exact: true }).click();
  const card = page.getByRole("button").filter({ has: page.getByRole("heading", { name: "Release notes", exact: true }) });
  const editor = page.getByRole("dialog", { name: "Edit resource" });
  await card.click();
  await editor.getByRole("button", { name: "Validate saved draft", exact: true }).click();
  await expect(editor.getByRole("status")).toContainText("Saved draft is valid");
  await editor.getByRole("button", { name: "Publish release", exact: true }).click();
  await expect(editor).not.toBeVisible();
  await card.click();
  await editor.getByRole("textbox", { name: "Draft JSON", exact: true }).fill('{"template":');
  await editor.getByRole("button", { name: "Publish release", exact: true }).click();
  await expect(editor.getByRole("alert")).toContainText("Specification must be valid JSON");
  await editor.getByRole("textbox", { name: "Draft JSON", exact: true }).fill('{"template":"Beta instructions"}');
  // Publishing must save the editor buffer, not silently publish the earlier draft.
  await editor.getByRole("button", { name: "Publish release", exact: true }).click();
  await expect(editor).not.toBeVisible();
  await card.click();
  await expect(editor.getByTestId("active-version")).toHaveText("v2");
  await editor.getByRole("combobox", { name: "Release version", exact: true }).selectOption("1");
  const differences = editor.getByRole("region", { name: "Specification differences" });
  await expect(differences).toContainText("/template");
  await expect(differences).toContainText("Alpha instructions");
  await expect(differences).toContainText("Beta instructions");
  await editor.getByRole("combobox", { name: "Compare with", exact: true }).selectOption("2");
  await expect(differences).toContainText("Beta instructions");
  await editor.getByRole("button", { name: "Activate v1", exact: true }).click();
  await expect(editor.getByTestId("active-version")).toHaveText("v1");
  await expect(editor.getByRole("textbox", { name: "Draft JSON", exact: true })).toHaveValue(/Beta instructions/);
  await editor.getByRole("button", { name: "Use v1 as draft", exact: true }).click();
  await editor.getByRole("button", { name: "Save draft", exact: true }).click();
  await expect(editor).not.toBeVisible();
  const resource = (await (await page.request.get("/api/v1/resources?search=Release%20notes")).json()).items[0];
  expect(resource.active_version).toBe(1);
  expect(resource.latest_version).toBe(2);
  expect(resource.draft.template).toBe("Alpha instructions");

  await page.getByRole("textbox", { name: "Search resources", exact: true }).fill("Release notes");
  await page.getByRole("button", { name: "Search", exact: true }).click();
  await card.click();
  await editor.getByRole("button", { name: "Archive resource", exact: true }).click();
  await expect(card).not.toBeVisible();
  await page.getByRole("combobox", { name: "Resource state", exact: true }).selectOption("true");
  await card.click();
  await expect(editor.getByTestId("active-version")).toHaveText("v1");
  await expect(editor.getByRole("button", { name: "Publish release", exact: true })).toHaveCount(0);
  await editor.getByRole("button", { name: "Restore resource", exact: true }).click();
  await expect(card).not.toBeVisible();
  await page.getByRole("combobox", { name: "Resource state", exact: true }).selectOption("false");
  await card.click();
  const before = await (await page.request.get(`/api/v1/resources/${resource.id}`)).json();
  const changed = await page.request.put(`/api/v1/resources/${resource.id}`, { headers: { "x-csrf-token": identity.csrf_token }, data: { revision: before.revision, name: before.name, spec: { template: "Gamma concurrent edit" } } });
  expect(changed.status()).toBe(200);
  await editor.getByRole("textbox", { name: "Name", exact: true }).fill("Stale title");
  await editor.getByRole("button", { name: "Publish release", exact: true }).click();
  await expect(editor.getByRole("alert")).toContainText("This draft changed");
  await expect(editor.getByRole("textbox", { name: "Name", exact: true })).toHaveValue("Stale title");
  await editor.getByRole("button", { name: "Discard edits and reload", exact: true }).click();
  await expect(editor.getByRole("textbox", { name: "Draft JSON", exact: true })).toHaveValue(/Gamma concurrent edit/);
  const final = await (await page.request.get(`/api/v1/resources/${resource.id}`)).json();
  expect(final.latest_version).toBe(2);
  expect(final.active_version).toBe(1);
  expect(errors).toEqual([]);
});

test("resource readers inspect releases without editing controls", async ({ page, browser }) => {
  const identity = await signInThroughUI(page);
  const headers = { "x-csrf-token": identity.csrf_token };
  const created = await page.request.post("/api/v1/resources", { headers, data: { kind: "prompt", name: "Reader reference", slug: "reader-reference", spec: { template: "Read only instructions" } } });
  expect(created.status()).toBe(201);
  const resource = await created.json();
  expect((await page.request.post(`/api/v1/resources/${resource.id}/publish`, { headers, data: { revision: resource.revision } })).status()).toBe(201);
  expect((await page.request.post("/api/v1/members", { headers, data: { name: "Resource reader", email: "resource-reader@example.test", password: "resource-reader-password", role: "viewer" } })).status()).toBe(201);
  const reader = await browser.newPage();
  try {
    await reader.goto("/");
    await reader.getByRole("textbox", { name: "Email", exact: true }).fill("resource-reader@example.test");
    await reader.getByLabel("Password", { exact: true }).fill("resource-reader-password");
    await reader.getByRole("button", { name: "Sign in", exact: true }).click();
    await reader.getByRole("button", { name: "03 Resources", exact: true }).click();
    await expect(reader.getByRole("button", { name: "+ New resource", exact: true })).toHaveCount(0);
    await reader.getByRole("button").filter({ has: reader.getByRole("heading", { name: "Reader reference", exact: true }) }).click();
    const editor = reader.getByRole("dialog", { name: "Edit resource" });
    await expect(editor.getByRole("textbox", { name: "Draft JSON", exact: true })).toHaveJSProperty("readOnly", true);
    await expect(editor.getByRole("combobox", { name: "Release version", exact: true })).toHaveValue("1");
    await expect(editor.getByRole("button", { name: "Save draft", exact: true })).toHaveCount(0);
    await expect(editor.getByRole("button", { name: "Publish release", exact: true })).toHaveCount(0);
    await expect(editor.getByRole("button", { name: "Archive resource", exact: true })).toHaveCount(0);
    await expect(editor.getByRole("button", { name: "Activate v1", exact: true })).toHaveCount(0);
  } finally { await reader.close(); }
});

test("resource creation keeps separate specifications per type and supports connections", async ({ page }) => {
  await signInThroughUI(page);
  await page.getByRole("button", { name: "03 Resources", exact: true }).click();
  await page.getByRole("button", { name: "+ New resource", exact: true }).click();
  const creator = page.getByRole("dialog", { name: "Create resource" });
  const kind = creator.getByRole("combobox", { name: "Type", exact: true });
  const spec = creator.getByRole("textbox", { name: "Specification JSON", exact: true });
  await kind.selectOption("bundle");
  await spec.fill('{"description":"My reusable bundle","tool_refs":[]}');
  await kind.selectOption("workflow");
  await expect(spec).toHaveValue(/"steps"/);
  await kind.selectOption("bundle");
  await expect(spec).toHaveValue('{"description":"My reusable bundle","tool_refs":[]}');
  await kind.selectOption("connection");
  await expect(spec).toHaveValue(/"base_url"/);
  await creator.getByRole("textbox", { name: "Name", exact: true }).fill("Example connector");
  await creator.getByRole("textbox", { name: "Slug", exact: true }).fill("example-connector");
  await spec.fill('{"adapter":"mcp","base_url":"https://connector.example.test/mcp","description":"Generic endpoint configuration"}');
  await creator.getByRole("button", { name: "Create draft", exact: true }).click();
  await page.getByRole("button").filter({ has: page.getByRole("heading", { name: "Example connector", exact: true }) }).click();
  const editor = page.getByRole("dialog", { name: "Edit resource" });
  await expect(editor.getByRole("textbox", { name: "Draft JSON", exact: true })).toHaveValue(/https:\/\/connector.example.test\/mcp/);
  await editor.getByRole("button", { name: "Publish release", exact: true }).click();
  await expect(editor).not.toBeVisible();
});
